config/routes.rb
Yesbaobei::Application.routes.draw do

  resources :user_articles

  match "provinces/display_all" => "provinces#display_all"

  resources :provinces do
    member do
      get 'show_cities_of_province'
    end
  end

  resources :cities

  resources :provinces

  resources :invitecodes

  resources :users do
    collection do
      get 'check_mail'
      get 'check_name'
      get 'check_invitecode'
      get 'user_confirmation'
      get 'login'
      get 'logout'
      post 'login_check'
    end
  end

  resources :users do
    member do
      get 'send_confirmation_mail'
      get 'main_page'
    end
  end

  resources :users

  resources :article_comment_replies

  resources :article_comments

  get "main/index"
  get "main/login"

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  resources :articles

  resources :boards

  root :to=> 'main#index', :as => 'main'

  resources :articles do
    member do
      post 'add_comment'
      get 'recommand'
      get 'add_favorite'
    end
  end

  resources :article_comments do
    member do
      get 'light'
    end
  end

end

app/models/article.rb
#coding: utf-8

class Article < ActiveRecord::Base
  belongs_to:board
  has_many:article_comments
  has_many :user_articles, :dependent => :destroy  #如果删除文章，则所有的收藏也被删除

  has_attached_file :avatar,
    :styles => {
      :small => "72x54#",
      :medium => "128x96#",
      :large => "256x192#"
      },
    :whiny => false,
    :url => "/uploadfiles/:class/:attachment/:id/:basename/:style.:extension",
    :path => ":rails_root/public/uploadfiles/:class/:attachment/:id/:basename/:style.:extension"

  validates_attachment_content_type :avatar,
      :content_type => ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png'],
      :message => "只允许图像文件"

  #文章被阅读一次
  def Article.read(article_id)
    article = Article.find(article_id)
    read_num = article.read_num ? article.read_num+1 : 1
    article.update_attribute(:read_num, read_num )
    return article
  end

  #文章被顶一次
  def Article.ding(article_id)
    article = Article.find(article_id)
    useful_num = article.useful_num ? article.useful_num+1 : 1
    article.update_attribute(:useful_num, useful_num )
    return article
  end

end

app/controllers/articles_controller.rb
# coding: utf-8
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.read(params[:id])
    @article_comments = ArticleComment.where("article_id = ? AND lighted = ?", @article.id, false).order("created_at DESC").paginate(:page => params[:page])
    @lighted_comments = ArticleComment.where("article_id = ? AND lighted = ?", @article.id, true).order("created_at DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    if params[:board_id]
      @article.board = Board.find(params[:board_id])
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])

  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end

  def add_comment
    redirect_to '/'
  end


  def recommand
    @article = Article.ding(params[:id])
    @floating_fade_message = "成功推荐！"
    respond_to do |format|
      format.js
    end

  end

  def add_favorite
     if @current_user
      #if UserArticle.find_by
      article = Article.find(params[:id])
      user_article = @current_user.user_articles.build(article)
      user_article.save
      @floating_fade_message = "收藏成功！"
    else
      @floating_fade_message = "当前用户已失效，请重新登录后收藏！"
    end

    respond_to do |format|
      format.js
      format.html # new.html.erb
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article_actions.html.erb
<% if @current_user %>
    <%=link_to "推荐", recommand_article_path, :remote=>true %>
    |
    <%=link_to "收藏", add_favorite_article_path, :remote => true %> |
<% else %>
    <a class='login_pop' href="#inline_login">推荐</a>
    |
    <a class='login_pop' href="#inline_login">收藏</a>
<% end %>
分享到:
<script type="text/javascript" charset="utf-8">
share_to_sina("<%=@article.title %>");
</script>

app/views/articles/_form.html.erb
<%= form_for(@article, :html=> {:multipart=>true}) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "文章标题(5-80字)" %><br />
    <%= f.text_field :title, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label "文章摘要(限120字)" %> <br />
    <%= f.text_area :abstract, :rows => 3, :cols => 70 %>
  </div>
  <div class="field">
    <%= f.label "所发表主版" %><br />
    <%= f.select :board_id, Board.all.collect {|b| [ b.try(:name), b.try(:id) ] }, {:include_blank => '请选择所发表的板块'} %>
  </div>
  <div>
    文章题图<br/>
    <%= image_tag (@article.avatar.url(:medium)) %><br/>
    <%= f.file_field :avatar, :class=>"uploadFileField"%>
  </div>


  <div class="field">
    <%= f.label "正文" %><br />
    <%= f.text_area :content, :id => "kindeditor"%>
  </div>

  <!--
  <div class="field">
    <%= f.label :read_num %><br />
    <%= f.text_field :read_num %>
  </div>
  <div class="field">
    <%= f.label :useful_num %><br />
    <%= f.text_field :useful_num %>
  </div>
  <div class="field">
    <%= f.label :star_score %><br />
    <%= f.text_field :star_score %>
  </div>
  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= kindeditor_javacript_include_tag %>

app/views/articles/_reply_article.html.erb
<div class="reply">
  <% if @current_user %>
      <% form_tag(article_comments_path) do %>
          <%= hidden_field_tag "article_id", @article.id %>
          <%= text_area_tag "replyContent", "" %> <br/>
          <%= submit_tag("留言")  %>
      <% end %>
    <%else%>
        <div id="login_first">
          <a class='login_pop' href="#inline_login">请登录后留言</a>
          或
          <%=link_to "快速注册", new_user_path %>
        </div>
    <%end%>

</div>

app/views/articles/add_favorite.js.erb
$("#floating_fade_message").html("<%=@floating_fade_message%>");
show_floating_fade_message();

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Abstract</th>
    <th>Read num</th>
    <th>Useful num</th>
    <th>Star score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= article.abstract %></td>
    <td><%= article.read_num %></td>
    <td><%= article.useful_num %></td>
    <td><%= article.star_score %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>发表新文章</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/recommand.js.erb
//设置div的位置
//document.getElementById("floating_fade_Message").style.top=(document.documentElement.scrollTop+(document.documentElement.clientHeight-document.getElementById("floating_fade_Message").offsetHeight)/2)+"px";
//document.getElementById("floating_fade_Message").style.left=(document.documentElement.scrollLeft+(document.documentElement.clientWidth-document.getElementById("floating_fade_Message").offsetWidth)/2)+"px";
$("#floating_fade_message").html("<%=@floating_fade_message%>");
$("#recommand_span").html("<%=@article.useful_num %>")
show_floating_fade_message();


app/views/articles/show.html.erb
<%= stylesheet_link_tag "article" %>

<div id="showArticleMain">
    <div id="articleRegion">
        <div id="title">
          <%= @article.title %>
        </div>
        <div id="authorRegion">
            <div id="authorAvatar">
                <%= image_tag("user-avatar.jpg") %>
            </div>
            <div id="authorInfo">
                ABC @ 2011-05-20 20:33:22
              <br/>
              阅读: <%=@article.read_num %> | 推荐: <span id="recommand_span"><%=@article.useful_num %></span> | 收藏: <span id="favorite_span">100</span> | 回复: <%= @article.article_comments.size %>
            </div>
            <div style="clear:both">
                <%= render :template => 'articles/_article_actions'%>
            </div>
        </div>
        <div id="abstractRegion">
          <div id="abstractAvatar">
            <%= image_tag (@article.avatar.url(:medium)) %>
          </div>
          <div id="abstract">
            <%= strip_tags @article.abstract %>
          </div>
          <div style="clear:both;"></div>
        </div>
        <div id="content">
            <%= raw(@article.content)%>
        </div>
        <div id="commentRegion">

            <%= render :template => 'articles/_reply_article'%>

            <% if @lighted_comments.size > 0 %>
                <div id="lightedCommentRegion">
                    <div id="lightedText"><strong>这些留言亮了:<%=@lighted_comments.size %></strong></div>
                    <% @lighted_comments.each do |article_comment| %>
                        <%= render(article_comment) %>
                    <%end%>
                </div>
            <% end %>

            <a name="comment"></a>
            <div id="commentList">
                <%= will_paginate @article_comments, :previous_label=>"上一页", :next_label=>"下一页"%>
                <% @article_comments.each do |article_comment| %>
                    <%= render(article_comment) %>
                <%end%>
            </div>
        </div>
    </div>


    <div id="rightPanel">

    </div>
</div>
<div style="clear:both">
  <%= will_paginate @article_comments, :previous_label=>"上一页", :next_label=>"下一页"%>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>

    <div style='display:none'>
      <div id='inline_content' style='padding:10px; background:#fff;'>
          <% form_tag article_comment_replies_path, :remote=>true do %>
              <%= hidden_field_tag "comment_id", @article.id %>
              <%= text_area_tag "commentReplyContent", "" %> <br/>
              <%= submit_tag "回复"%>
          <% end %>
      </div>
    </div>
</div>
<%= render :template => 'common_partials/floating_fade_message' %>

<% content_for :js_loaded do  %>
    <%= javascript_include_tag "page_js/replycomment" %>
<% end %>