config/routes.rb
Yesbaobei::Application.routes.draw do

  resources :user_articles

  match "provinces/display_all" => "provinces#display_all"

  resources :provinces do
    member do
      get 'show_cities_of_province'
    end
  end

  resources :cities

  resources :provinces

  resources :invitecodes

  resources :users do
    collection do
      get 'check_mail'
      get 'check_name'
      get 'check_invitecode'
      get 'user_confirmation'
      get 'login'
      get 'logout'
      post 'login_check'
    end
  end

  resources :users do
    member do
      get 'send_confirmation_mail'
      get 'main_page'
    end
  end

  resources :users

  resources :article_comment_replies

  resources :article_comments

  get "main/index"
  get "main/login"

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  resources :articles

  resources :boards

  root :to=> 'main#index', :as => 'main'

  resources :articles do
    member do
      post 'add_comment'
      get 'recommand'
      get 'add_favorite'
    end
  end

  resources :article_comments do
    member do
      get 'light'
    end
  end

end

app/models/user.rb
# coding: utf-8
class User < ActiveRecord::Base
  belongs_to :city
  has_many :user_articles


  has_attached_file :avatar,
    :styles => {
      :small => "45x45#",
      :medium => "100x100#",
      :temp => "45x45#",
      },
    :whiny => false,
    :url => "/uploadfiles/:class/:attachment/:id/:style.:extension",
    :path => ":rails_root/public/uploadfiles/:class/:attachment/:id/:style.:extension"

  validates_attachment_content_type :avatar,
      :content_type => ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png'],
      :message => "只允许jpg/gif/png的图片上传"

  #确定用户是否有回复的权限
  def can_reply
    true
  end

  #验证用户是否存在或者是否为合法用户
  def User.authenticate(user_name, password)
    users = User.where("email = ? AND password = ?", user_name, password)
    if users.size > 0
      return users.first
    else
      return nil
    end
  end

  #用户的状态，是由status和confirmed两个属性共同决定的
  def life_status
    if !status
      "disable"
    else
      if confirmed
        "normal"
      else
        "unconfirmed"
      end
    end
  end

  #判断用户是否属于有效状态
  def is_effecitve
    life_status == "normal"
  end

end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @show_login = false
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    @user.status= true  #设定用户状态为有效
    @user.confirmed = false
    @code = UUIDTools::UUID.random_create
    @user.confirm_code = @code.to_str

    respond_to do |format|
      if @user.save
        #设定认证码信息
        @invite_code = Invitecode.find_by_code(params["inviteCode"])
        if @invite_code
          @invite_code.status = false
          @invite_code.enable_date= DateTime.current
          @invite_code.enable_user_id=@user.id
          @invite_code.save
        end

        #todo:自动建立互粉关系

        format.html { redirect_to send_confirmation_mail_user_path(@user)}
        #format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        @current_user = @user
        @fade_message = "用户信息更新成功！"
        format.html { render :action => "main_page" }
        format.xml  { head :ok }
        #实现文件上传的Ajax
        format.js {respond_to_parent{render :file => "/users/renew_avatar.js.erb"}}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  # GET method
  # Check the register mail
  def check_mail
    @user = User.find_by_email(params[:user][:email])

    respond_to do |format|
      format.json  { render :json => !@user }
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET method
  # check the name
  def check_name
     @user = User.find_by_name(params[:user][:name])

    respond_to do |format|
      format.json  { render :json => !@user }
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET method
  # check the invite code
  def check_invitecode
    @codes = Invitecode.where("code = ? AND status = ?", params["inviteCode"], true)

    @valid = @codes.size > 0
    #@valid = true
    respond_to do |format|
      format.json  { render :json => @valid }
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  #注册用户确认
  def user_confirmation
    @result = "s"  #success

    @user = User.find(params["userid"])

    if !@user
      @result = "e1"  #error1: no this user
    else
      if @user.confirmed
        @result = "e2"  #error2: has been confirmed
      else
        if @user.confirm_code != params["confirm_code"]
          @result = "e1"
        end
      end
    end

    if @result == "s"
      @user.confirmed= true
      @user.save()
      #generate invite codes for this user
      InvitecodesController.generate_invite_codes(@user.id,20)
    end

    respond_to do |format|
        format.html
    end
  end

  #send confirmation_mail for the user
  def send_confirmation_mail
    @user = User.find(params[:id])
    if (@user)
      Notifier.register_confirm(@user).deliver
      respond_to do |format|
          format.html
      end
    end
  end

  #用户登录页面
  def login
    @error = false
    @show_login = false
    @source_type = params["source_type"]
    @source_page = params["source_page"]

    #如果登录不是来源于弹出框的话，登录成功后就转到用户首页
    if (@source_type != "partial")
      @source_type = "normal"
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  #处理用户的登录信息
  def login_check
    @error = false
    @source_type = params["source_type"]
    @source_page = params["source_page"]
    @login_name = params["loginName"]
    @show_login = false
    user = User.authenticate(params["loginName"], params["password"])
    respond_to do |format|
      if !user    #登录验证失败
        @error = true
        @error_message = "您的登录信息有误，请检查后再次登录"
        format.html do
          render :action => "login"
        end
        #如果是用Ajax方式登录
        format.js do
          render :file => "/users/js_user_login_failure.js.erb"
        end
      else #用户验证通过
        session[:user_id] = user.id
        format.html do
          if @source_type == "normal"
            redirect_to main_page_user_path(user)
          else
            redirect_to @source_page
          end
        end

        #如果是用Ajax方式登录
        format.js do
          @submitter_id = params["submitter_id"]
          @click_id = params["click_id"]
          render :file => "/users/js_user_login_success.js.erb"
        end

      end
    end
  end

  def logout
    session.delete :user_id
    redirect_to :back
  end

  #用户首页
  def main_page
    if user_login_authorize
      @current_user
      respond_to do |format|
        format.html
      end
      end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label '电子邮箱' %> [用您常用的邮箱进行注册，一个邮箱只能注册一次]
    <br />
    <%= f.text_field :email, :class=>"actionTextInput", :size=>'30' %>
  </div>
  <div class="field">
    <%= f.label '设定密码' %><br />
    <%= f.text_field :password, :size=>'30' %>
  </div>

  <div class="field">
    <%= f.label '重复密码' %><br />
    <%= text_field_tag "repeatPassword", '', :size=>'30' %>
  </div>

  <div class="field">
    <%= f.label '你的网名' %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label '邀 请 码' %><br />
    <%= text_field_tag "inviteCode" %>
  </div>

  <div class="actions">
    <%= f.submit '注册' %>
  </div>
<% end %>

app/views/users/_normal_main_page.html.erb
<%= stylesheet_link_tag "setting" %>
<div>
  <h1><%=@current_user.name %>的账号管理</h1>
  <%= render :template => 'common_partials/fade_message' %>
  <br/>
  <table>
      <tr>
        <td width="70px">
          <%= label_tag '头像:' %>
        </td>
        <td>
          <% if !@current_user.avatar_file_name %>
            <%= image_tag "/images/default_user_avatar.jpg" %> <br/>
          <%else%>
            <%= image_tag @current_user.avatar.url(:small), :id=>"avatar" %>
          <%end%>
          <a href="#" class="action" id="reset_avatar">修改</a>
        </td>
      </tr>
    <tr>
      <td width="70px">
      </td>
      <td>
        <div id="div_reset_avatar">
          <%= form_for(@current_user, :url => user_path(:format => 'js') , :remote => true, :html=> {:multipart=>true, :target =>"upload_frame"}) do |f| %>
             <%= f.file_field :avatar, :class=>'file_upload'%>
             <%=f.submit("上传")%>
          <% end %>
        </div>
      </td>
    </tr>
  </table>

  <%= form_for(@current_user) do |f| %>
    <table>
      <tr>
        <td width="70px">
          <%= f.label '登录邮箱:' %>
        </td>
        <td>
          <%= @current_user.email %> <a href="#" class="action" id="change_email">修改邮箱</a>  <br/>
          <div class="action" id="div_change_email">
            <%= f.text_field :email, :size => 50 %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label '网上名称:' %>
        </td>
        <td>
          <%= @current_user.name %>  <a href="#" class="action" id="change_name">修改</a>
          <div class="action" id="div_change_name">
            <%= f.text_field :name, :size => 20 %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label '常住城市:' %>
        </td>
        <td>
          <span id="span_city"><%= @current_user.city_name %></span>  <a href="#" class="action" id="change_city">修改</a>
          <%= f.hidden_field :city_name%>
          <%= f.hidden_field :city_id%>
          <div class="action" id="div_change_city">
                <%= render :template => 'users/_show_location' %>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label '自我介绍:' %>
        </td>
        <td>
          <%= f.text_area :self_desc, :rows => 3, :cols => 70 %> <br/>
          (还可以输入<span id="desc_count">80</span>字)
        </td>
      </tr>

      <tr>
        <td>
          <%= f.label '签名:' %>
        </td>
        <td>
          <%= f.text_area :signature, :rows => 2, :cols => 70 %>
          (还可以输入<span id="signature_count">80</span>字)
        </td>
      </tr>

    </table>
    <div class="actions">
        <%= f.submit '更新' %>
    </div>
  <% end %>
</div>
<iframe id='upload_frame' name="upload_frame" style="width:1px;height:1px;border:0px" src="about:blank"></iframe>


app/views/users/_show_location.html.erb
<%if @current_user.city %>
    <% @cities = City.find_all_by_province_id(@current_user.city.province_id) %>
    <%= render :template => 'cities/_show_cities' %>
<%else%>
    <%= render :template => 'provinces/_show_provinces' %>
<%end%>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th>Name</th>
    <th>City</th>
    <th>Score</th>
    <th>Avatar</th>
    <th>Level</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.name %></td>
    <td><%= user.city %></td>
    <td><%= user.score %></td>
    <td><%= user.avatar %></td>
    <td><%= user.level %></td>
    <td><%= user.status %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/js_user_login_success.js.erb
window.location.reload();

app/views/users/login.html.erb
<h1>欢迎登录</h1>    <br/>

<%if @error %>
    <div class="error"><%=@error_message%></div><br/>
<%end %>

<% form_tag login_check_users_path, :id=>'loginForm' do %>
  邮箱 <%= text_field_tag "loginName",@login_name?@login_name:"", :size=>30%> <br/><br/>
  密码 <%= password_field_tag "password","", :size=>30%> <br/><br/>
  <%= hidden_field_tag "source_type", @source_type %>
  <%= hidden_field_tag "source_page", @source_page %>
  <%= submit_tag "登录"%>
<% end %>

<% content_for :js_loaded do  %>
    <%= javascript_include_tag "plugins/jquery.validate.min" %>
    <%= javascript_include_tag "plugins/additional-methods.min" %>
    <%= javascript_include_tag "plugins/validation_message_cn" %>
    <%= javascript_include_tag "page_js/user_login" %>
<% end %>

app/views/users/login_partial.html.erb
<!--用于显示登录界面-->

<div style='display:none'>
  <div id='inline_login' style='padding:10px; background:#fff;'>
        <% form_tag login_check_users_path, :id=>'loginForm' do %>
          邮箱 <%= text_field_tag "loginName", "", :size=>25 %> <br/><br/>
          密码 <%= password_field_tag "password", "", :size=>25%> <br/><br/>
          <%= hidden_field_tag "source_type", "partial" %>
          <%= hidden_field_tag "source_page", request.request_uri %>
          <%= hidden_field_tag "submitter_id", "" %>
          <%= hidden_field_tag "click_id", "" %>
          <%= submit_tag "登录"%>
          <%=link_to "注册新用户", new_user_path %>
        <% end %>
        <ul id="errorBox"></ul>
  </div>

</div>

<% content_for :js_loaded do  %>
    <%= javascript_include_tag "plugins/jquery.validate.min" %>
    <%= javascript_include_tag "plugins/additional-methods.min" %>
    <%= javascript_include_tag "plugins/validation_message_cn" %>
    <%= javascript_include_tag "page_js/user_login_partial" %>
<% end %>

app/views/users/new.html.erb
<div id="normalAction">
  <h1>欢迎加入</h1>
  <div class="fieldRegion">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', users_path %>

<% content_for :js_loaded do  %>
    <%= javascript_include_tag "plugins/jquery.validate.min" %>
    <%= javascript_include_tag "plugins/additional-methods.min" %>
    <%= javascript_include_tag "plugins/validation_message_cn" %>
    <%= javascript_include_tag "page_js/user_register" %>
<% end %>

app/views/users/renew_avatar.js.erb
$("#avatar").attr("src","<%=@current_user.avatar.url(:temp)%>");

app/views/users/send_confirmation_mail.html.erb
<p>
  认证邮件已经发送到<%=@user.email %>,请尽快查收并完成认证，以便全面使用我们所提供的服务。谢谢！
</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>City:</b>
  <%= @user.city_name %>
</p>

<p>
  <b>City_id:</b>
  <%= @user.city_id %>
</p>

<p>
  <b>Score:</b>
  <%= @user.score %>
</p>

<p>
  <b>Avatar:</b>
  <%= @user.avatar %>
</p>

<p>
  <b>Level:</b>
  <%= @user.level %>
</p>

<p>
  <b>Status:</b>
  <%= @user.status %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/user_confirmation.html.erb
<% case @result %>
    <% when "s" %>
        <%= render :template => 'users/_user_confirmation_pass' %>
    <% when "e1"%>
        <%= render :template => 'users/_user_confirmation_failure' %>
    <% when "e2"%>
        <%= render :template => 'users/_user_confirmed' %>
<%end%>

app/views/users/validate.js.erb
$("#email-validation").html("通过！");