config/routes.rb
Yesbaobei::Application.routes.draw do

  resources :user_articles

  match "provinces/display_all" => "provinces#display_all"

  resources :provinces do
    member do
      get 'show_cities_of_province'
    end
  end

  resources :cities

  resources :provinces

  resources :invitecodes

  resources :users do
    collection do
      get 'check_mail'
      get 'check_name'
      get 'check_invitecode'
      get 'user_confirmation'
      get 'login'
      get 'logout'
      post 'login_check'
    end
  end

  resources :users do
    member do
      get 'send_confirmation_mail'
      get 'main_page'
    end
  end

  resources :users

  resources :article_comment_replies

  resources :article_comments

  get "main/index"
  get "main/login"

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  resources :articles

  resources :boards

  root :to=> 'main#index', :as => 'main'

  resources :articles do
    member do
      post 'add_comment'
      get 'recommand'
      get 'add_favorite'
    end
  end

  resources :article_comments do
    member do
      get 'light'
    end
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :province
  has_many :user;
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.xml
  def index
    @cities = City.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.xml
  def show
    @city = City.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.xml
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.xml
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to(@city, :notice => 'City was successfully created.') }
        format.xml  { render :xml => @city, :status => :created, :location => @city }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @city.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.xml
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to(@city, :notice => 'City was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @city.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.xml
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to(cities_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :province_id %><br />
    <%= f.text_field :province_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/_show_cities.html.erb
<%@cities.each do |c| %>
    <%= link_to c.name, main_path, :class=>"set_city", :method => "get" , :value=>c.id%> |
<%end%>
<div style="text-align:right">
  <%=link_to "其他省市...", provinces_display_all_path, :method=>"get", :remote=>true %>
</div>

<%= javascript_include_tag "page_js/set_cities" %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <tr>
    <th>Province</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.province_id %></td>
    <td><%= city.name %></td>
    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'Destroy', city, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Province:</b>
  <%= @city.province_id %>
</p>

<p>
  <b>Name:</b>
  <%= @city.name %>
</p>


<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>