config/routes.rb
Yesbaobei::Application.routes.draw do

  resources :user_articles

  match "provinces/display_all" => "provinces#display_all"

  resources :provinces do
    member do
      get 'show_cities_of_province'
    end
  end

  resources :cities

  resources :provinces

  resources :invitecodes

  resources :users do
    collection do
      get 'check_mail'
      get 'check_name'
      get 'check_invitecode'
      get 'user_confirmation'
      get 'login'
      get 'logout'
      post 'login_check'
    end
  end

  resources :users do
    member do
      get 'send_confirmation_mail'
      get 'main_page'
    end
  end

  resources :users

  resources :article_comment_replies

  resources :article_comments

  get "main/index"
  get "main/login"

  get 'kindeditor/images_list'

  post 'kindeditor/upload'

  resources :articles

  resources :boards

  root :to=> 'main#index', :as => 'main'

  resources :articles do
    member do
      post 'add_comment'
      get 'recommand'
      get 'add_favorite'
    end
  end

  resources :article_comments do
    member do
      get 'light'
    end
  end

end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :city
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  # GET /provinces
  # GET /provinces.xml
  def index
    @provinces = Province.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @provinces }
    end
  end

  # GET /provinces/1
  # GET /provinces/1.xml
  def show
    @province = Province.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @province }
    end
  end

  # GET /provinces/new
  # GET /provinces/new.xml
  def new
    @province = Province.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @province }
    end
  end

  # GET /provinces/1/edit
  def edit
    @province = Province.find(params[:id])
  end

  # POST /provinces
  # POST /provinces.xml
  def create
    @province = Province.new(params[:province])

    respond_to do |format|
      if @province.save
        format.html { redirect_to(@province, :notice => 'Province was successfully created.') }
        format.xml  { render :xml => @province, :status => :created, :location => @province }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @province.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /provinces/1
  # PUT /provinces/1.xml
  def update
    @province = Province.find(params[:id])

    respond_to do |format|
      if @province.update_attributes(params[:province])
        format.html { redirect_to(@province, :notice => 'Province was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @province.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.xml
  def destroy
    @province = Province.find(params[:id])
    @province.destroy

    respond_to do |format|
      format.html { redirect_to(provinces_url) }
      format.xml  { head :ok }
    end
  end

  def show_cities_of_province
    @cities = City.where("province_id = ?", params[:id])

    respond_to do |format|
      format.html { redirect_to(cities_url) }
      format.xml  { head :ok }
      format.js
    end
  end

  def display_all
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provinces/_show_provinces.html.erb
<% Province.all.each do |p| %>
    <%= link_to p.name, show_cities_of_province_province_path(p), :method => "get", :remote => true, :value=>p.id %> |
<%end%>

app/views/provinces/display_all.js.erb
$("#div_change_city").html("<%= escape_javascript(render :template => 'provinces/_show_provinces')%>");

app/views/provinces/edit.html.erb
<h1>Editing province</h1>

<%= render 'form' %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<h1>Listing provinces</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @provinces.each do |province| %>
  <tr>
    <td><%= province.name %></td>
    <td><%= link_to 'Show', province %></td>
    <td><%= link_to 'Edit', edit_province_path(province) %></td>
    <td><%= link_to 'Destroy', province, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Province', new_province_path %>

app/views/provinces/new.html.erb
<h1>New province</h1>

<%= render 'form' %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @province.name %>
</p>


<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/show_cities_of_province.js.erb
$("#div_change_city").html("<%= escape_javascript(render :template => 'cities/_show_cities')%>");